# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Teender' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Firebase'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'

  # Pods for Teender

  target 'TeenderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TeenderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
